aws:
  region: 'us-west-2'
  instance_type: 't2.small'

# make sure the platform versions are actually strings
platforms:
  centos:
    '7.5.1804':
      ami: 'ami-19007261'
    '7.4.1708':
      ami: 'ami-02c71d7a'
  ubuntu:
    '14.04':
      ami: 'ami-c59ce2bd'
    '16.04':
      ami: 'ami-db710fa3'
    '17.10':
      ami: 'ami-2192f559'
    '18.04':
      ami: 'ami-22741f5a'
  amazon:
    '2':
      ami: 'ami-a9d09ed1'
    '2018.03':
      ami: 'ami-e251209a'
    '2017.03':
      ami: 'ami-215dbe59'
    '2017.09':
      ami: 'ami-f64bdf8e'
    '2016.09':
      ami: 'ami-9e73ccfe'
    '2016.03':
      ami: 'ami-d8f704b8'
    '2015.09':
      ami: 'ami-42b15122'
    '2015.03':
      ami: 'ami-d1c5d1e1'
  redhat:
    '7.5':
      ami: 'ami-28e07e50'
    '7.4':
      ami: 'ami-9fa343e7'
    '7.3':
      ami: 'ami-6f68cf0f'
    '6.9':
      ami: 'ami-d61a92b6'
    '6.8':
      ami: 'ami-6fb7450f'
  suse:
    '12.3':
      ami: 'ami-6bc56f13'
    '12.2':
      ami: 'ami-974357ee'
    '12.1':
      ami: 'ami-61ad6501'
    '11.4':
      ami: 'ami-7eb31906'
